# Generated by Django 3.2.7 on 2021-10-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtosell',
            name='category',
            field=models.ForeignKey(blank=True, default='Others', null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='itemtosell',
            name='title',
            field=models.CharField(default='title', max_length=128),
        ),
    ]
