# Generated by Django 3.2.7 on 2021-10-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211020_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtosell',
            name='onFire',
            field=models.BooleanField(default=False),
        ),
    ]
