# Generated by Django 3.2.7 on 2021-10-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_itemtosell_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-active']},
        ),
    ]
